# Generated by Django 6.0.3 on 2026-03-28 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('time', models.TimeField(verbose_name='Время')),
                ('periodicity_days', models.PositiveIntegerField(verbose_name='Дней периодичности')),
                ('execution_time_seconds', models.PositiveIntegerField(verbose_name='Время на выполнение (сек)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная')),
                ('last_done', models.DateTimeField(blank=True, null=True, verbose_name='Последнее выполнение')),
                ('streak', models.PositiveIntegerField(default=0, verbose_name='Серия')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_habits', to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['time'],
            },
        ),
    ]
