# Generated by Django 6.0.3 on 2026-03-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_pleasant',
            field=models.BooleanField(default=False, verbose_name='Приятная привычка'),
        ),
        migrations.AddField(
            model_name='habit',
            name='place',
            field=models.CharField(default='Дом', max_length=255, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='last_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Дней периодичности'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
