# Generated by Django 6.0.3 on 2026-04-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_is_pleasant_habit_place_alter_habit_last_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
